pipeline {
    agent {
        docker {
            image 'node:6-alpine'
            args '-p 3000:3000'
        }
    }
    environment {
        CI = 'true'
    }
    stages {
        stage('Checkout') {
            steps {
                // Checkout the repository
                checkout scm: [
                    $class: 'GitSCM',
                    branches: [[name: '*/master']],  // Or the appropriate branch you want to build from
                    userRemoteConfigs: [[url: 'https://github.com/patebija/simple-node-project.git', credentialsId: 'Jenkins']]
                ]
            }
        }
        stage('Build') {
            steps {
                sh 'npm install'
            }
        }
        stage('Test') {
            steps {
                sh './jenkins/scripts/test.sh'
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
                input message: 'Finished using the web site? (Click "Proceed" to continue)'
                sh './jenkins/scripts/kill.sh'
            }
        }
    }
}
